#!/usr/bin/env python3
"""
Regenerates DESTINATION_NOTES_PLAN.md — the tracking overview for the per-destination-notes
project (see .claude/agents/destination-notes-researcher.md).

Groups every destination across every route by (country_code, sorted destination names) — a
"signature". Two routes with an identical signature share the exact same destination list, so
researching it once and pasting the same notes into both is free extra coverage (see the Jordan
pilot: one research pass covered Jordan, Mediterranean Civilizations Expedition, and Egypt &
Arabian Peninsula at once). Signatures reused by 2+ routes are listed first — highest leverage,
tackle those before the one-off routes.

Checks the actual current live state (via simulate_route_builder.js, the same "what would a
fresh browser really end up with" simulation used elsewhere in this repo) to mark each signature
[x] done or [ ] not started, so this file can just be regenerated after every batch instead of
hand-maintained.

Usage:
    python3 scripts/generate_destination_notes_plan.py
"""
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / 'DESTINATION_NOTES_PLAN.md'


def main():
    raw = subprocess.run(
        ['node', 'scripts/simulate_route_builder.js'],
        cwd=REPO_ROOT, capture_output=True, check=True,
    ).stdout
    routes = json.loads(raw.decode('utf-8'))

    # signature -> {routes: set(route_name), destinations: [names in order], filled: bool}
    sigs = {}
    for r in routes:
        for b in r.get('blocks', []):
            code = b.get('country_code', '')
            dests = b.get('destinations', [])
            names = tuple(d.get('name', '') for d in dests)
            if not names:
                continue
            key = (code, tuple(sorted(names)))
            entry = sigs.setdefault(key, {'routes': set(), 'destinations': list(names), 'filled': None})
            entry['routes'].add(r['name'])
            all_filled = all(d.get('notes', '').strip() for d in dests)
            # A signature counts as filled only if every instance of it is filled — if any route
            # still shows empty notes for the same signature, treat the whole signature as open
            # so it doesn't get silently skipped in a later batch.
            entry['filled'] = all_filled if entry['filled'] is None else (entry['filled'] and all_filled)

    shared = {k: v for k, v in sigs.items() if len(v['routes']) > 1}
    solo = {k: v for k, v in sigs.items() if len(v['routes']) == 1}

    total_dest_unique = sum(len(v['destinations']) for v in sigs.values())
    total_dest_raw = sum(len(v['destinations']) * len(v['routes']) for v in sigs.values())
    done_sigs = sum(1 for v in sigs.values() if v['filled'])

    lines = []
    lines.append('# Destination Notes — Tracking Plan')
    lines.append('')
    lines.append(f'Auto-generated by `scripts/generate_destination_notes_plan.py` — regenerate after '
                  f'every batch rather than hand-editing this file (except the intro prose above the '
                  f'stats, which is preserved by re-running the script after any manual tweaks are '
                  f'copied back in). Do NOT `Read` this file whole — it lists all '
                  f'{len(sigs)} unique destination-sets across the app; grep for a country code, a '
                  f'route name, or a destination name instead.')
    lines.append('')
    lines.append('See `.claude/agents/destination-notes-researcher.md` for what actually gets '
                  'researched per destination, and CLAUDE.md/CHANGELOG.md for the Jordan pilot batch '
                  'this plan is based on (2026-09-16).')
    lines.append('')
    lines.append('## Status')
    lines.append('')
    lines.append(f'- **{len(routes)} routes total**, {total_dest_raw} destination-slots raw, but only '
                  f'**{len(sigs)} unique (country + destination-list) signatures = {total_dest_unique} '
                  f'unique destinations** need real research — the rest is the same content reused '
                  f'across routes.')
    lines.append(f'- **{len(shared)} shared signatures** (reused by 2+ routes, {sum(len(v["destinations"]) for v in shared.values())} '
                  f'destinations) — covering {sum(len(v["routes"]) for v in shared.values())} route-instances. '
                  f'Do these first: one research pass, paste into every route listed.')
    lines.append(f'- **{len(solo)} solo signatures** (used by exactly 1 route, '
                  f'{sum(len(v["destinations"]) for v in solo.values())} destinations) — each needs its own dedicated batch.')
    lines.append(f'- **Done so far: {done_sigs} / {len(sigs)} signatures.**')
    lines.append('')

    def fmt_entry(key, v):
        code, names_sorted = key
        checkbox = '[x]' if v['filled'] else '[ ]'
        dest_list = ', '.join(v['destinations'])
        route_list = ', '.join(sorted(v['routes']))
        return f"- {checkbox} **{code}** ({len(v['destinations'])} dest): {dest_list} — routes: {route_list}"

    lines.append('## Shared signatures (do these first)')
    lines.append('')
    lines.append('Sorted by how many routes reuse them — highest leverage first.')
    lines.append('')
    for key, v in sorted(shared.items(), key=lambda kv: (-len(kv[1]['routes']), kv[0][0])):
        lines.append(fmt_entry(key, v))
    lines.append('')

    lines.append('## Solo signatures (one route each)')
    lines.append('')
    lines.append('Sorted alphabetically by country code.')
    lines.append('')
    for key, v in sorted(solo.items(), key=lambda kv: (kv[0][0], list(kv[1]['routes'])[0])):
        lines.append(fmt_entry(key, v))
    lines.append('')

    # ---- Batch queue: "what to actually do next" ----
    # Per-route leverage score: for every block, how many OTHER routes share that exact
    # signature (len(routes)-1), summed. A route whose blocks are heavily reused by other
    # routes (the ~13 original "grand expeditions" standalone/split routes were carved out of)
    # scores high — doing it fills itself AND cascades to everything reusing it, same effect
    # the Eurasia Grand Tour batch had (142 destinations -> 507 slots across 53 routes).
    route_blocks = defaultdict(list)  # route_name -> [(signature_key, dest_count, filled)]
    for key, v in sigs.items():
        for route_name in v['routes']:
            route_blocks[route_name].append((key, len(v['destinations']), v['filled']))

    route_stats = []
    for route_name, blocks in route_blocks.items():
        total_dest = sum(d for _, d, _ in blocks)
        remaining_dest = sum(d for _, d, filled in blocks if not filled)
        if remaining_dest == 0:
            continue  # fully done already
        leverage = sum(len(sigs[key]['routes']) - 1 for key, _, filled in blocks if not filled)
        route_stats.append((route_name, remaining_dest, total_dest, leverage, len(blocks)))

    # Rank by leverage first (how many other routes benefit), then by remaining size.
    route_stats.sort(key=lambda t: (-t[3], -t[1]))

    lines.append('## Batch queue — what to do next')
    lines.append('')
    lines.append('Every route ranked by "leverage" (how many *other* routes share at least one of '
                  'its not-yet-done blocks — doing this route cascades to those too, the same effect '
                  'the Eurasia Grand Tour batch had) and by how many destinations are still open. Work '
                  'top to bottom. For anything over ~40 remaining destinations, split it into 3-5 '
                  'geographic/thematic sub-batches and dispatch them in parallel (see the Eurasia '
                  'pilot in CHANGELOG.md for the exact pattern: research each sub-batch with a '
                  'separate agent call, then insert everything and write one migration together once '
                  'all sub-batches are back).')
    lines.append('')
    lines.append('| Route | Remaining / total destinations | Other routes that benefit (leverage) |')
    lines.append('|---|---|---|')
    for route_name, remaining, total, leverage, nblocks in route_stats[:40]:
        lines.append(f'| {route_name} | {remaining}/{total} | {leverage} |')
    if len(route_stats) > 40:
        lines.append(f'| ... {len(route_stats) - 40} more routes with open destinations ... | | |')
    lines.append('')
    lines.append('Once every route above shows 0 leverage (i.e. nothing left is shared — only true '
                  'solo routes remain), just work straight down the "Solo signatures" list above, in '
                  'any convenient grouping (by continent works well, mirroring the existing '
                  '`rbSeedStandaloneCountryRoutesBatch1-9` groupings).')
    lines.append('')

    OUTPUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUTPUT} ({len(sigs)} signatures: {len(shared)} shared, {len(solo)} solo; {done_sigs} done)')


if __name__ == '__main__':
    main()
